### ISSUE TITLE
sh3eb-elf-gcc fatal error

### ISSUE THREAD

**Issue by Oderjunkie** [Jonimoose/libfxcg#41] opened 2020-04-28 02:40 UTC
im using windows 10 64bit and in the powershell window got this error:
sh3eb-elf-gcc: fatal error: cannot execute 'c:/users/compunet/downloads/prizmsdk-win-0.5/prizmsdk-win-0.5/bin/../lib/gcc/sh3eb-elf/9.3.0/../../../../sh3eb-elf/bin/as.exe': CreateProcess: No such file or directory
compilation terminated.
make[1]: *** [C:/Users/CompuNet/Downloads/PrizmSDK-win-0.5/PrizmSDK-win-0.5/toolchain/prizm_rules:64: example.o] Error 1
make: *** [Makefile:104: all] Error 2

**Comment by tari** [comment] 2020-04-28 03:03
Looks like GCC needs to be told to use `sh3eb-elf-as` rather than just `as`. Need to look into the relevant configure options when building the toolchain.

**Comment by tari** [comment] 2020-04-28 03:08
I assume that because GCC is trying to run the assembler your project contains an assembly file (or multiple). Is that right?

**Comment by tari** [comment] 2020-04-28 03:38
Building with a .S file doesn't do this for me, so I'm not sure how to reproduce.

Can you share what your project looks like?

**Comment by Oderjunkie** [comment] 2020-04-29 21:02
[Files with error](https://www.mediafire.com/file/vjsu5nw2ef5uafm/PrizmSDK-win-0.5.rar/file)

**Comment by tari** [comment] 2020-05-02 05:16
The example project in the archive you provided compiles fine on my system. Were you trying to build another project that you didn't include, or were you having trouble with the example one?

**Comment by tari** [comment] 2020-05-30 05:41
Closing this since I haven't been able to reproduce. If you're still having the problem please reopen and provide a way to reproduce.

**Closed by tari** 2020-05-30 05:41 UTC
Labels: Toolchain
